# Generated by Django 4.1.6 on 2023-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAG_prezentare', '0002_prezentare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prezentare',
            name='image',
            field=models.ImageField(upload_to='PAG_prezentare/files/covers'),
        ),
    ]
